[package]
name = "socketcan"
version = "3.5.0"
edition = "2021"
rust-version = "1.70"
authors = [
    "Marc Brinkmann <git@marcbrinkmann.de>",
    "Frank Pagliughi <fpagliughi@mindspring.com>"
]
documentation = "https://docs.rs/socketcan"
repository = "https://github.com/mbr/socketcan-rs"
license = "MIT"
description = """
Linux SocketCAN library. Send and receive CAN frames via CANbus on Linux.
"""

# Features:
#
# "netlink" (default) - Whether to include CAN interface configuration 
#       capabilities based on netlink kernel communications
# "dump" (default) - Whether to include 'candump' log file parsing 
#	capabilities.
# "enumerate" - Ability to enumerate the available CAN network interfaces
#
# "utils" - Build the command-line utilities
#
# "tokio" - Async/await support with tokio
# "async-io" - Async/await support with async-io
# "async-std" - Async/await support for async-std using async-io
# "smol" - Async/await support for smol using async-io
#

[features]
default = []
vcan_tests = []
tokio = ["dep:tokio", "dep:futures"]

[dependencies]
embedded-can = "0.4"
nb = "1"
itertools = "0.14"
libc = "0.2"
nix = { version="0.31", features = ["poll", "process", "net"] }
bitflags = "2"
thiserror = "2"
socket2 = { version = "0.6", features = ["all"] }
tokio = { version = "1", features = ["net"], optional = true }
futures = { version = "0.3", optional = true }

[dev-dependencies]
anyhow = "1"
ctrlc = "3"
nb = "1"
futures-timer = "3"
futures-util = "0.3"
serial_test = { version = "3", features = ["async"]}
async-std = { version = "1", features = ["attributes"]}
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "io-util"] }
futures = "0.3"

[[example]]
name = "tokio_send"
required-features = ["tokio"]

[[example]]
name = "tokio_bridge"
required-features = ["tokio"]

[[example]]
name = "tokio_print_frames"
required-features = ["tokio"]

[[example]]
name = "tokio_average"
required-features = ["tokio"]
